[test]
# Preload setup file before running tests
preload = ["./src/__tests__/setup.ts"]

# Enable coverage reporting
coverage = true
coverageDir = "coverage"
smol = true
# Use happy-dom for tests
testEnvironment = "happy-dom"
